gateway:
  backend:
    image:
      name: tomaugspurger/pangeo-multicloud
      tag: "2020.05.12.1"
      pullPolicy: IfNotPresent

    scheduler:
      extraPodConfig:
        tolerations:
          - key: "k8s.dask.org/dedicated"
            operator: "Equal"
            value: "scheduler"
            effect: "NoSchedule"
          - key: "k8s.dask.org_dedicated"
            operator: "Equal"
            value: "scheduler"
            effect: "NoSchedule"
    worker:
      extraPodConfig:
        tolerations:
          - key: "k8s.dask.org/dedicated"
            operator: "Equal"
            value: "worker"
            effect: "NoSchedule"
          - key: "k8s.dask.org_dedicated"
            operator: "Equal"
            value: "worker"
            effect: "NoSchedule"
