gateway:
  backend:
    scheduler:
      extraPodConfig:
        tolerations:
          - key: "k8s.dask.org/dedicated"
            operator: "Equal"
            value: "scheduler"
            effect: "NoSchedule"
          - key: "k8s.dask.org_dedicated"
            operator: "Equal"
            value: "scheduler"
            effect: "NoSchedule"
    worker:
      extraPodConfig:
        tolerations:
          - key: "k8s.dask.org/dedicated"
            operator: "Equal"
            value: "worker"
            effect: "NoSchedule"
          - key: "k8s.dask.org_dedicated"
            operator: "Equal"
            value: "worker"
            effect: "NoSchedule"
